### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by maroo1746** [BytingTigers/Server#13]
안녕하세요, TEAM 7의 서버를 구동하던 중 다음과 같은 오류를 마주쳤고, README file에도 추가적인 설명이 없어 질문드립니다. 

혹시 다음과 같은 오류에 어떻게 대처하면 될까요? 

seoye@SYLEE MINGW64 /c/2023_2/Software_Security/vuln/team7/Server (main)
$ docker run -p 5000:5000 -p 5001:5001 server
exec /start.sh: no such file or directory

**Comment by taiki-okano** [comment]
Can you please write in English next time?

**Comment by maroo1746** [comment]
oh okay!

I have faced some problems when I run the Server container. How can I deal with the following errors?

seoye@SYLEE MINGW64 /c/2023_2/Software_Security/vuln/team7/Server (main)
$ docker run -p 5000:5000 -p 5001:5001 server
exec /start.sh: no such file or directory

**Comment by taiki-okano** [comment]
Make sure to clone it before build and run, try the commands below:

```
$ git clone git@github.com:BytingTigers/Server.git
$ cd Server
$ make
$ docker run -p 5000:5000 -p 5001:5001 -it server
```
